version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: date > current_date.txt
      - persist_to_workspace:
          root: ./
          paths:
          - current_date.txt
      - continuation/continue:
          configuration_path: .circleci/subconfig.yml

workflows:
  setup:
    jobs:
      - setup
