version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: date > current_date.txt && cat current_date.txt
      - save_cache:
          key: subcommand-cache-{{ checksum "current_date.txt" }}
          paths:
            - current_date.txt
      - continuation/continue:
          configuration_path: .circleci/subconfig.yml
          parameters: "{cache_key: subcommand-cache-{{ checksum current_date.txt }}}"

workflows:
  setup:
    jobs:
      - setup
