version: 2.1

parameters:
  cache_key:
    type: string

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo Hello, subconfig!
      - restore_cache:
          key: "<< pipeline.parameters.cache_key >>"
      - run: cat current_date.txt

workflows:
  build:
    jobs:
      - hello
