version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo Hello, subconfig!
      - restore_cache:
          key: subcommand-cache-{{ .BuildNum }}
      - run: cat current_date.txt

workflows:
  build:
    jobs:
      - hello
