version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo Hello, subconfig!
      - attach_workspace:
          at: ./
      - run: cat current_date.txt

workflows:
  build:
    jobs:
      - hello
